# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ghactl

before:
  hooks:
    - go mod download

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

signs:
  - artifacts: all
    cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
